"""add 'type' column to verification table

Revision ID: 11127faa8f2e
Revises: 87598b7cd55a
Create Date: 2025-08-25 14:06:22.299229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11127faa8f2e'
down_revision = '87598b7cd55a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        
    op.execute("UPDATE verifications SET type = 'verification'")
    
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.alter_column(sa.Column('type', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
